# Copyright (c) 2021-2021 The Pastel Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

[package]
name = "rq-service"
version = "0.1.0"
authors = ["ayk"]
edition = "2018"

[dependencies]
# raptorQ
raptorq = "1.6.3"
#raptorq = {git = "https://github.com/pastelnetwork/raptorq"}
#raptorq = {path = "../raptorq"}

# Config
clap = "2.33.3"
config = "0.11.0"
dirs = "3.0.2"
serde_derive = "1.0.125"
serde = "^1.0.8"
flexi_logger = { version = "0.18", features = ["async"] }
log = "0.4"

# gRPC server/client
tonic = "0.4.3"
prost = "0.7.0"

#Async
tokio = {version = "1.5.0", features = ["full"]}
tokio-stream ="0.1.5"

# other
bs58 = "0.4.0"
sha3 = "0.9.1"
rand = "0.8.4"
uuid = {version = "0.8.2", features = ["v4"]}
itertools = "0.10.1"

[build-dependencies]
tonic-build = "0.4.2"
