version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.53.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Create temp files for testing
          command: |
            mkdir test;
            dd if=/dev/urandom of=test/10_000 bs=1 count=10000;
            dd if=/dev/urandom of=test/10_000_000 bs=1 count=10000000;
            dd if=/dev/urandom of=test/10_000_001 bs=1 count=10000001;
      - run:
          name: Run Tests
          command: "cargo test --release"